jwt:
  secret: Cizo4#l&f

server:
  port: 3001

spring:
  data:
    mongodb:
      host: localhost
      database: camisola10
      port: 27017

logging:
  level:
    org:
      springframework:
        data: DEBUG

aws:
  bucketName: camisola-backend
  accessKey: AKIAJJHJUDSTSR7BJ5MQ
  accessKeySecret: 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
  region: eu-west-1
