aws:
  bucketName: camisola-backend
  bucketPath: images
  accessKey: ${AWS_ACCESS_KEY}
  accessKeySecret: ${AWS_ACCESS_SECRET}
  region: eu-west-1

spring:
  data:
    mongodb:
      host: mongo
      database: camisola10
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      port: 27017
      auto-index-creation: false

jwt:
  secret: ${JWT_SECRET}
  expiration-time: 86400000 # 1 day
