aws:
  bucketName: camisola-backend
  bucketPath: images-test
  accessKey: ${AWS_ACCESS_KEY}
  accessKeySecret: ${AWS_ACCESS_SECRET}
  region: eu-west-1

spring:
  data:
    mongodb:
      host: localhost
      database: camisola10
      port: 27017

jwt:
  secret: ${JWT_SECRET}
  expiration-time: 864000000 # 10 days
