server:
  port: 3001

spring:
  data:
    mongodb:
      host: localhost
      database: camisola10
      port: 27017

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: SecretKeyToGenJWTs
  expiration-time: 864000000 # 10 days