aws:
  bucketName: camisola-backend
  bucketPath: images
  accessKey: ${AWS_ACCESS_KEY}
  accessKeySecret: ${AWS_ACCESS_SECRET}
  region: eu-west-1

#spring:
#  data:
#    mongodb:
#      uri: mongodb://${DB_USER}:${DB_PASSWORD}@ds151247.mlab.com:51247/camisola10?retryWrites=false

spring:
  data:
    mongodb:
      host: mongo
      database: camisola10
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      port: 27017

jwt:
  secret: ${JWT_SECRET}
  expiration-time: 864000000 # 10 days
