logging:
  level:
    org:
      springframework:
        security: DEBUG
        transaction:
          interceptor: TRACE

spring:
#  profiles:
#    include: email
  data:
    mongodb:
      host: localhost
      database: camisola10
      port: 27017
      auto-index-creation: false

jwt:
  secret: SecretKeyToGenJWTs
  expiration-time: 3600000 # 1h
