logging:
  level:
    org:
      springframework:
        security: DEBUG
        transaction:
          interceptor: TRACE

spring:
  data:
    mongodb:
      host: localhost
      database: camisola10
      port: 27017
      auto-index-creation: false

jwt:
  secret: SecretKeyToGenJWTs
  expiration-time: 180000 # 3min
