jwt:
  secret: Cizo4#l&f

logging:
  level:
    org:
      springframework:
        data: DEBUG

aws:
  bucketName: camisola-backend
  accessKey: ${AWS_ACCESS_KEY}
  accessKeySecret: ${AWS_ACCESS_SECRET}
  region: eu-west-1
