jwt:
  secret: Cizo4#l&f

server:
  port: 3001

spring:
  data:
    mongodb:
      host: localhost
      database: camisola10
      port: 27017

logging:
  level:
    org:
      springframework:
        data: DEBUG

