aws:
  bucketName: camisola-backend
  bucketPath: images-test
  accessKey: ${AWS_ACCESS_KEY}
  accessKeySecret: ${AWS_ACCESS_SECRET}
  region: eu-west-1

#spring:
#  data:
#    mongodb:
#      uri: mongodb://${DB_USER}:${DB_PASSWORD}@ds223019.mlab.com:23019/camisola10-staging?retryWrites=false

spring:
  data:
    mongodb:
      host: localhost
      database: camisola10
      port: 27017

jwt:
  secret: ${JWT_SECRET}
  expiration-time: 864000000 # 10 days
