# Java Gradle CircleCI 2.0 configuration file
#
version: 2
#executors:
#  docker-publisher:
#    environment:
#      IMAGE_NAME: joe7lopes/camisola10
#      JVM_OPTS: -XX:MaxRAM=300m

jobs:
  build:
    docker:
      - image: openjdk:11
    steps:
      - checkout
      - run:
          name: Run Tests
          command: gradle clean build
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$IMAGE_NAME:$TAG
      - run:
          name: Deploy app to Linode Producrion Server via Docker
          command: |
            echo "ssh to digital ocean"